version: "3.5"
services:
  nginx:
    labels:
      - traefik.enable=false
      - traefik.http.routers.{{.reward_env_name}}-nginx.priority=2

  varnish:
    hostname: "{{.reward_env_name}}-varnish"
    image: {{default "docker.io/rewardenv" .reward_docker_image_base}}/varnish:{{default "6.0" .varnish_version}}
    depends_on:
      - nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{.reward_env_name}}-varnish.tls=true
      - traefik.http.routers.{{.reward_env_name}}-varnish.priority=1
      - traefik.http.routers.{{.reward_env_name}}-varnish.rule=
          HostRegexp(`{subdomain:.+}.{{.traefik_domain}}`) || Host(`{{.traefik_domain}}`)
      - traefik.http.services.{{.reward_env_name}}-varnish.loadbalancer.server.port=80
