---
name: Docker Image PHP
on:
  schedule:
  - cron: "0 6 1 * *"
  push:
    paths:
    - images/.trigger
    - images/php/**
    - images/php-fpm/**
    branches:
    - main
jobs:
  php:
    name: PHP ${{ matrix.php_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["5.6", "7.0", "7.1", "7.2", "7.3", "7.4", "8.0"]
        include:
          # IonCube and Source Guardian loaders do not yet exist for PHP 8.0
          - php_version: "8.0"
            php_variants: "cli cli-debian fpm fpm-debian"
    steps:
      - uses: actions/checkout@v1
      - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
        env:
          BUILD_GROUP: php
          VERSION_LIST: ${{ matrix.php_version }}
          VARIANT_LIST: ${{ matrix.php_variants }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  php-fpm:
    name: FPM ${{ matrix.php_version }}
    runs-on: ubuntu-latest
    needs: php
    strategy:
      matrix:
        php_version: ["5.6", "7.0", "7.1", "7.2", "7.3", "7.4", "8.0"]
        include:
          # IonCube and Source Guardian loaders do not yet exist for PHP 8.0
          - php_version: "8.0"
            php_variant: "fpm"
    steps:
    - uses: actions/checkout@v1
    - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
      env:
        BUILD_GROUP: php-fpm
        PHP_VERSION: ${{ matrix.php_version }}
        PHP_VARIANT: ${{ matrix.php_variant }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  magento1:
    name: PHP-FPM ${{ matrix.php_version }} (magento1)
    runs-on: ubuntu-latest
    needs: php-fpm
    strategy:
      matrix:
        php_version: ["5.6", "7.0", "7.1", "7.2", "7.3", "7.4", "8.0"]
        build_group: ["magento1", "magento1-debian"]
    steps:
    - uses: actions/checkout@v1
    - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
      env:
        BUILD_GROUP: php-fpm/${{ matrix.build_group }}
        PHP_VERSION: ${{ matrix.php_version }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  magento2:
    name: PHP-FPM ${{ matrix.php_version }} (magento2)
    runs-on: ubuntu-latest
    needs: php-fpm
    strategy:
      matrix:
        php_version: ["7.0", "7.1", "7.2", "7.3", "7.4", "8.0"]
        build_group: ["magento2", "magento2-debian"]
    steps:
    - uses: actions/checkout@v1
    - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
      env:
        BUILD_GROUP: php-fpm/${{ matrix.build_group }}
        PHP_VERSION: ${{ matrix.php_version }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  magento2-web:
    name: PHP-FPM ${{ matrix.php_version }} (magento2-web)
    runs-on: ubuntu-latest
    needs: magento2
    strategy:
      matrix:
        php_version: ["7.0", "7.1", "7.2", "7.3", "7.4", "8.0"]
        build_group: ["magento2-web"]
    steps:
      - uses: actions/checkout@v1
      - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
        env:
          BUILD_GROUP: php-fpm/${{ matrix.build_group }}
          PHP_VERSION: ${{ matrix.php_version }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  wordpress:
    name: PHP-FPM ${{ matrix.php_version }} (wordpress)
    runs-on: ubuntu-latest
    needs: php-fpm
    strategy:
      matrix:
        php_version: ["5.6", "7.0", "7.1", "7.2", "7.3", "7.4", "8.0"]
        build_group: ["wordpress", "wordpress-debian"]
    steps:
      - uses: actions/checkout@v1
      - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
        env:
          BUILD_GROUP: php-fpm/${{ matrix.build_group }}
          PHP_VERSION: ${{ matrix.php_version }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  shopware:
    name: PHP-FPM ${{ matrix.php_version }} (shopware)
    runs-on: ubuntu-latest
    needs: php-fpm
    strategy:
      matrix:
        php_version: ["7.3", "7.4", "8.0"]
        build_group: ["shopware", "shopware-debian"]
    steps:
      - uses: actions/checkout@v1
      - run: ./images/scripts/build.sh --push "${BUILD_GROUP}"
        env:
          BUILD_GROUP: php-fpm/${{ matrix.build_group }}
          PHP_VERSION: ${{ matrix.php_version }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
